[package]
name = "obs-gamepad"
version = "0.1.0"
edition = "2021"

[lib]
name = "gamepad"
crate-type = ["cdylib"]

[dependencies]
obs-wrapper = { git = "https://github.com/bennetthardwick/rust-obs-plugins" }
tiny-skia = "0.6"
gilrs-core = "0.3"
log = "0.4"
minifb = "0.19"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
notify = "4"

[profile.release]
lto = "thin"
panic = "abort"
