[package]
name = "obs-gamepad"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# obs-wrapper = {git = "https://github.com/bennetthardwick/rust-obs-plugins"}
obs-wrapper = { path = "../rust-obs-plugins" }
tiny-skia = "0.6.1"
gilrs-core = "0.3.1"
log = "0.4.14"
minifb = "0.19.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
