# inactive = "#123"
# active = "#828"
# outline = "#282828"
# outline_weight = 1.5
# gate_radius = 50

[button_shape]
type = "circle"
radius = 20

[[button]] # A
id = 2
fill_active = '#f00'
pos = [400, 150]

[[button]] # B
id = 1
fill_active = '#ff0'
pos = [350, 200]

[[button]] # X
id = 3
fill_active = '#00f'
pos = [350, 100]

[[button]] # Y
id = 0
fill_active = '#0f0'
pos = [300, 150]

[[button]] # LT
id = 6
type = "rounded_rect"
pos = [100, 20]
size = [80, 40]
radius = 10

[[button]] # RT
id = 7
type = "rounded_rect"
pos = [200, 20]
size = [80, 40]
radius = 10

[[button]] # LB
id = 4
type = "rounded_rect"
pos = [20, 20]
size = [80, 40]
radius = 10

[[button]] # RB
id = 5
type = "rounded_rect"
pos = [300, 20]
size = [80, 40]
radius = 10

[[button]] # +
id = 9
pos = [250, 110]
type = "circle"
radius = 10

[[button]] # -
id = 8
pos = [200, 110]
type = "circle"
radius = 10

[[button]] # home
id = 13
pos = [250, 140]
type = "circle"
radius = 10

[[button]] # capture
id = 14
pos = [200, 140]
type = "circle"
radius = 10

[[stick]]
x_axis = 0
y_axis = 1
pos = [100, 150]
gate = "#282828"
gate_radius = 66
gate_weight = 3.1
displacement = 50

[[stick]]
x_axis = 2
y_axis = 3
pos = [280, 260]
radius = 30
gate = "#282828"
gate_weight = 2
gate_radius = 40
displacement = 30

[[axis]] # dpad x
id = 4
pos = [75, 275]
invert = true
size = [80, 10]

[[axis]] # dpad y
id = 5
pos = [110, 240]
invert = true
size = [10, 80]
fill_dir = "top_to_bottom"
