buttons = [
  { id = 0, pos = [20, 20] },   # left side, top down
  { id = 1, pos = [20, 60] },
  { id = 2, pos = [20, 100] },
  { id = 3, pos = [20, 140] },
  { id = 4, pos = [20, 180] },
  { id = 5, pos = [20, 220] },
  { id = 6, pos = [20, 260] },
  { id = 7, pos = [20, 300] },
  { id = 8, pos = [20, 340] },
  { id = 9, pos = [20, 380] },
  { id = 10, pos = [20, 420] },
  { id = 11, pos = [20, 460] },
  { id = 12, pos = [20, 500] },
  { id = 13, pos = [20, 540] },
  { id = 14, pos = [20, 580] },
  { id = 15, pos = [20, 620] },
]


axes = [
  { id = 0, pos = [50, 10] },  # right side, top down
  { id = 1, pos = [50, 50] },
  { id = 2, pos = [50, 90] },
  { id = 3, pos = [50, 130] },
  { id = 4, pos = [50, 170] },
  { id = 5, pos = [50, 210] },
  { id = 6, pos = [50, 250] },
  { id = 7, pos = [50, 290] },
]
